# Initial setup of IAM for local project
tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
      WORKSPACE_ROOT: /Users/mac/Documents/AWSProjects
    before: |
      cd /Documents
      curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
      sudo installer -pkg AWSCLIV2.pkg -target /
      cd $WORKSPACE_ROOT
      
